# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package ucurses;
use base qw(Exporter);
use base qw(DynaLoader);
package ucursesc;
bootstrap ucurses;
package ucurses;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package ucurses;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package ucurses;


############# Class : ucurses::CursesGui ##############

package ucurses::CursesGui;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( ucurses );
%OWNER = ();
%ITERATORS = ();
*helloworld = *ucursesc::CursesGui_helloworld;
*getLines = *ucursesc::CursesGui_getLines;
*newMenu = *ucursesc::CursesGui_newMenu;
*showMenu = *ucursesc::CursesGui_showMenu;
*wait_for_key = *ucursesc::CursesGui_wait_for_key;
*printBox = *ucursesc::CursesGui_printBox;
*printTitle = *ucursesc::CursesGui_printTitle;
*printAt = *ucursesc::CursesGui_printAt;
*printAtWindow = *ucursesc::CursesGui_printAtWindow;
*print_in_middle = *ucursesc::CursesGui_print_in_middle;
*colorbox = *ucursesc::CursesGui_colorbox;
*setcolor = *ucursesc::CursesGui_setcolor;
*messageBox = *ucursesc::CursesGui_messageBox;
*yesno = *ucursesc::CursesGui_yesno;
*print_centered = *ucursesc::CursesGui_print_centered;
*newWindow = *ucursesc::CursesGui_newWindow;
*moveWindow = *ucursesc::CursesGui_moveWindow;
*delWindow = *ucursesc::CursesGui_delWindow;
*dialogBox = *ucursesc::CursesGui_dialogBox;
*wclrscr = *ucursesc::CursesGui_wclrscr;
*wCenterTitle = *ucursesc::CursesGui_wCenterTitle;
*fileView = *ucursesc::CursesGui_fileView;
*execView = *ucursesc::CursesGui_execView;
*fileViewIPC = *ucursesc::CursesGui_fileViewIPC;
sub new {
    my $pkg = shift;
    my $self = ucursesc::new_CursesGui(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        ucursesc::delete_CursesGui($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package ucurses;

1;
